### ISSUE TITLE
Draft requirements document

### ISSUE THREAD

**Issue by barisozcanli** [swe574-2015fall-group2/core_repo#14]

**Comment by cakyel** [comment]
RSD draft document has been updated. Please check and add your own remarks.

https://docs.google.com/document/d/1cDOhDOtD-PbiHid1lgJ5Xg82piPBxJQW5LMeiwCR-UU/edit

**Comment by cakyel** [comment]
RSD Draft is here:
https://piazza.com/class/if3ll4yun9p306?cid=30
