### ISSUE TITLE
[MILESTONE 7] Search Management - Search User

### ISSUE THREAD

**Issue by cakyel** [swe574-2015fall-group2/core_repo#146]
Search User functions should be completed based on RSD, DSD and mockups.

**Comment by mehmetcelikel** [comment]
"query" method is implemented in user service.

**Comment by ssurucu** [comment]
@mehmetcelikel we can use it for invite list in "create meeting" also, right? I will search in users and invite some of them, so I can get the user list from this method?

**Comment by cakyel** [comment]
@mehmetcelikel  @ssurucu  Have you agreed on the requirements of this issue? Is it all completed?

**Comment by mehmetcelikel** [comment]
Yes, this is all completed. searchUser service will be used by frontend.

**Comment by cakyel** [comment]
Thank you!
