### ISSUE TITLE
Back End - Front End Integration & Bugfixing

### ISSUE THREAD

**Issue by cakyel** [swe574-2015fall-group2/core_repo#162]
Back end and front end should be integrated and any resulting buxfixing should be done.

Mainly Barış, Mehmet, Sinan and Recep are responsible.

**Comment by barisozcanli** [comment]
Task is so vague. What will be done here? What is the estimation? What is the definiton of done for this task?
For every bug, an issue must be opened an assigned.

**Comment by cakyel** [comment]
You are right Barış, but we have to specify this issue in advance right? Because even if the estimation is not clear, there will be integration and bugfixing issues to be.

Please help me - all group members - about how can we elicit this issue in a better way.

**Comment by cakyel** [comment]
Here are the bug issues related to this topic. This issue will serve as a merger when planning the next week. I am commenting the bugs here and closing this issue.

Static content should be removed from Groups Page #2
https://github.com/swe574-2015fall-group2/webapp_repo/issues/2

Create meeting parameters #179
https://github.com/swe574-2015fall-group2/core_repo/issues/179

Read Meeting Service #180
https://github.com/swe574-2015fall-group2/core_repo/issues/180

Group names must be unique #175
https://github.com/swe574-2015fall-group2/core_repo/issues/175

ListAllGroups and ListMyGroups can't be listed #185
https://github.com/swe574-2015fall-group2/core_repo/issues/185

Tag attribute is missing from Groups,Meetings,Notes and Discussions #187
https://github.com/swe574-2015fall-group2/core_repo/issues/187

User model has duplicate variable #183
https://github.com/swe574-2015fall-group2/core_repo/issues/183

ListMyGroups result doesn't return groupdata #181
https://github.com/swe574-2015fall-group2/core_repo/issues/181

ListAllGroups and ListMyGroups can't be listed #185
https://github.com/swe574-2015fall-group2/core_repo/issues/185

User should join the group when group is created #189 
https://github.com/swe574-2015fall-group2/core_repo/issues/189

Groups are missing picture attribute #186 
https://github.com/swe574-2015fall-group2/core_repo/issues/186

Registration Page - Form controls are missing #8
https://github.com/swe574-2015fall-group2/webapp_repo/issues/8

My Profile Page - Missing Edit Profile Function #9
https://github.com/swe574-2015fall-group2/webapp_repo/issues/9

Group listing services must have an area for status "joined:true/false" #188
https://github.com/swe574-2015fall-group2/core_repo/issues/188
