### ISSUE TITLE
[BUG] Web Project - Registration Page

### ISSUE THREAD

**Issue by cakyel** [swe574-2015fall-group2/core_repo#182]
In the registration page, system accepts invalid e-mail address and does not check password field with the re-type password field.

https://onedrive.live.com/redir?resid=1571C717A54B2868!6575&authkey=!AC4qebyBIfew02A&v=3&ithint=photo%2cpng

**Comment by ssurucu** [comment]
@cakyel can you open the issues that directly related to web project, under web project repo? it will be easy to follow, we are following our bug/cr from there;
https://github.com/swe574-2015fall-group2/webapp_repo/issues

**Comment by ssurucu** [comment]
I opened related issue under web project 

Related issue: https://github.com/swe574-2015fall-group2/webapp_repo/issues/8
