### ISSUE TITLE
[BUG] Web Project - My Profile page

### ISSUE THREAD

**Issue by cakyel** [swe574-2015fall-group2/core_repo#184]
Edit profile button is missing in the My Profile page.

**Comment by ssurucu** [comment]
@cakyel can you open the issues that directly related to web project, under web project repo? it will be easy to follow, we are following our bug/cr from there;
https://github.com/swe574-2015fall-group2/webapp_repo/issues

**Comment by ssurucu** [comment]
I opened related issue under web project

Related issue: https://github.com/swe574-2015fall-group2/webapp_repo/issues/9
