### ISSUE TITLE
Front End -  All Groups should be able to be viewed

### ISSUE THREAD

**Issue by cakyel** [swe574-2015fall-group2/core_repo#195]
This issue is created for milestone tracking, see the original issue below:

https://github.com/swe574-2015fall-group2/webapp_repo/issues/5

**Comment by ssurucu** [comment]
@cakyel what is the issue here? is there an error while viewing the all groups?

**Comment by cakyel** [comment]
@ssurucu can you look at the details which @barisozcanli specified in the original issue?

https://github.com/swe574-2015fall-group2/webapp_repo/issues/5

**Comment by ssurucu** [comment]
fixed
