### ISSUE TITLE
Backend - Group's ListAll service return the same result of ListMyGroups service

### ISSUE THREAD

**Issue by OrkunKocyigit** [swe574-2015fall-group2/core_repo#199]

**Comment by barisozcanli** [comment]
investigating...

**Comment by barisozcanli** [comment]
@OrkunKocyigit , I couldn't reproduce the issue. Results of ListAllGroups and ListMyGroups don't seem same. Could you please check again or give me the username you're trying with?

**Comment by OrkunKocyigit** [comment]
I cannot reproduce it again too so I am closing the issue
