### ISSUE TITLE
Front End - Logout button should be added.

### ISSUE THREAD

**Issue by cakyel** [swe574-2015fall-group2/core_repo#205]
Logout button is missing in the design.

https://github.com/swe574-2015fall-group2/webapp_repo/issues/11

**Comment by mehmetcelikel** [comment]
logout service is added to backend.

**Comment by cakyel** [comment]
https://github.com/swe574-2015fall-group2/core_repo/issues/206

**Comment by ssurucu** [comment]
fixed
