### ISSUE TITLE
Backend - Group's ListRecommendedGroups are returning response code 500

### ISSUE THREAD

**Issue by OrkunKocyigit** [swe574-2015fall-group2/core_repo#236]
Hello,
The request JSON is given below:
{
  "authToken": "2d7b9490-a0fa-11e5-bf6b-0401862bab01"
}
The swagger return this response:
{
  "status": "error",
  "consumerMessage": "Group not found",
  "applicationMessage": ""
}
However when it is used in the application is also returns response code 500 henceforth it throws an exception when it is trying to getting read.

**Comment by barisozcanli** [comment]
@OrkunKocyigit can you check it please?

**Comment by OrkunKocyigit** [comment]
Hello @barisozcanli ,
Problem still exist as it is,
![nope](https://cloud.githubusercontent.com/assets/10797423/11766736/330c022a-a19d-11e5-9359-24d04e0b23ad.png)

**Comment by barisozcanli** [comment]
one more please? @OrkunKocyigit

**Comment by cakyel** [comment]
This issue should be reopened until we get Orkun's approval.

**Comment by OrkunKocyigit** [comment]
Hello,
Yeah issue is fixed. Thanks.
