### ISSUE TITLE
Backend - Meeting model's queryByGroup method returns response code 500 if no meetings exist

### ISSUE THREAD

**Issue by OrkunKocyigit** [swe574-2015fall-group2/core_repo#238]
Hello,
The request JSON is given below:
{
  "authToken": "5897fe90-a1ca-11e5-b196-0401862bab01",
  "id": "566c6380e4b038c20f1ddd08"
}
The swagger return this response:
{
  "status": "error",
  "consumerMessage": "Meeting not found",
  "applicationMessage": ""
}
 When this method has used in the application, it returns response code 500 henceforth it causes an exception when it has been processed.

**Comment by OrkunKocyigit** [comment]
This service still throws response code 500
![nope](https://cloud.githubusercontent.com/assets/10797423/11768938/8e038256-a1e4-11e5-8924-cb72418b9646.png)

**Comment by OrkunKocyigit** [comment]
Hello,
Are there any updates on this issue?

**Comment by barisozcanli** [comment]
@OrkunKocyigit could you please check it?
