### ISSUE TITLE
Backend - User model's uploadPicture method returns response code 500

### ISSUE THREAD

**Issue by OrkunKocyigit** [swe574-2015fall-group2/core_repo#239]
Hello,
The request is given below: (WARNING:IT IS LONG)
http://pastebin.com/fmDLGQHy
If anyone wonders, picture is Adriana Lima. You can reconstruct the Base64 String with using online services. (For this picture, I can get the image back successfully). It throws response code 500 as well. You cannot test this on swagger.
Good luck.

**Comment by mehmetcelikel** [comment]
Can you try it again? I think that was related with folder permissions of our application. I modified OS folder permissions for our user.

**Comment by OrkunKocyigit** [comment]
Hello,
This problem is fixed.
