### ISSUE TITLE
Backend - Resource upload function is not working

### ISSUE THREAD

**Issue by ssurucu** [swe574-2015fall-group2/core_repo#242]
Request URL
http://162.243.215.160:9000/v1/resource/upload?groupId=56676d00e4b026a4a9922007&authToken=361a3f90-a288-11e5-afbb-0401862bab01

Response Body
{
  "status": "error",
  "applicationMessage": "Internal Server Error"
}

Response Code
500

Response Headers
{
  "Content-Type": "application/json;charset=UTF-8"
}

**Comment by barisozcanli** [comment]
@ssurucu when I test it, it seems it's working on production from swagger. Can you test it again? maybe it was a temorary thing. And also there is no such a group with groupId=56676d00e4b026a4a9922007, but even if the groupId is wrong error message must be something else, so I think It's not about groupId.

**Comment by cakyel** [comment]
Can you close this issue if it is not recurring? @ssurucu

**Comment by cakyel** [comment]
Kind reminder to @ssurucu
