### ISSUE TITLE
Query resources should be working also with meeting,note and discussion id not just group id

### ISSUE THREAD

**Issue by ssurucu** [swe574-2015fall-group2/core_repo#255]
The resource list can also come in query note, disscussion and note, it will solve the problem in another way.

**Comment by barisozcanli** [comment]
@ssurucu I added noteId to to query, now the request is like this :
{
  "authToken": "string",
  "groupId": "string",
  "noteId": "string"
}

You should send either groupId or noteId, whichever you need.
I'll add resources to discussion and meeting creation. then I'll add them to query as well.

**Comment by barisozcanli** [comment]
@ssurucu discussion and meeting resources can also be queried from the same service as below request:
{
  "authToken": "string",
  "groupId": "string",
  "noteId": "string",
  "meetingId": "string",
  "discussionId": "string"
}
And also, resources for note, meeting, discussion and groups are existed in their respective objects. I mean when you query a discussion, resources are also retrieved with that object.
