### ISSUE TITLE
UpdateGroup Throws Internal Server Error

### ISSUE THREAD

**Issue by OrkunKocyigit** [swe574-2015fall-group2/core_repo#258]
Request:
{
	"authToken": "3aa56c90-af37-11e5-9dcc-04019494e201",
	"description": "This is a group for star wars lovers",
	"tagList": [{
		"clazz": "TelevisionShow",
		"tag": "Cinema Insomnia"
	}],
	"name": "Star Wars Lovers"
}
Response:
{
  "status": "error",
  "applicationMessage": "Internal Server Error"
}

**Comment by barisozcanli** [comment]
I think it was a temporary error because of the server change. I tested it, it seems there's no error. could you please check it? @OrkunKocyigit

**Comment by OrkunKocyigit** [comment]
No problemo
