### ISSUE TITLE
Add a Comment to a Note - Needed

### ISSUE THREAD

**Issue by ssurucu** [swe574-2015fall-group2/core_repo#261]
As in discussion detail, we need a function to add comment to a note.

https://github.com/swe574-2015fall-group2/webapp_repo/issues/103

**Comment by OrkunKocyigit** [comment]
They weren't any comments for the notes in DSD or RSD as far as I remember. When did this requirement changed?

**Comment by barisozcanli** [comment]
@ssurucu @cakyel  guys, do we need this as @OrkunKocyigit  says?

**Comment by cakyel** [comment]
@barisozcanli I have checked the RSD and I think we missed this feature, but it would be great if you can implement it.

**Comment by OrkunKocyigit** [comment]
Then what is the difference between Discussion and Note?

**Comment by cakyel** [comment]
You are right @OrkunKocyigit 

Then comment box should be removed from Note Details page if @barisozcanli and @ssurucu also agree on this.
