### ISSUE TITLE
Group's create service tag attribute should be renamed

### ISSUE THREAD

**Issue by OrkunKocyigit** [swe574-2015fall-group2/core_repo#264]
Tag attribute of the Group's response is like this:
tagList": [
        {
          "tag": "string",
          "clazz": "string"
        }
]
Literally every other services it is like this:
tagList": [
        {
          "label": "string",
          "clazz": "string"
        }
]
Can we rename Group model's tag attribute for consistency (and preventing my auto parsers from crashing)

**Comment by barisozcanli** [comment]
@recepgunay53 does it effect frontend web?

**Comment by OrkunKocyigit** [comment]
It will.

**Comment by OrkunKocyigit** [comment]
Semantic model's services still has name label btw

**Comment by OrkunKocyigit** [comment]
We decided it is not really important for now, I will try to locally fix it.
