### ISSUE TITLE
Duplicate tags in semantic's querySearchString

### ISSUE THREAD

**Issue by OrkunKocyigit** [swe574-2015fall-group2/core_repo#265]
Request:
{
  "authToken": "b62e56f0-b16d-11e5-9444-04019494e201",
  "queryString": "Banana"
}
Response:
{
  "status": "success",
  "result": {
    "dataList": [
      {
        "label": "Canaan Banana",
        "clazz": null,
        "description": null
      },
      {
        "label": "Canaan Banana",
        "clazz": "President",
        "description": null
      },
      {
        "label": "Sean Banan",
        "clazz": null,
        "description": null
      },
      {
        "label": "Te Urewera National Park",
        "clazz": "ProtectedArea",
        "description": null
      },
      {
        "label": "Journey (band)",
        "clazz": null,
        "description": null
      },
      {
        "label": "Java Man",
        "clazz": "Mammal",
        "description": null
      },
      {
        "label": "Java (programming language)",
        "clazz": "ProgrammingLanguage",
        "description": null
      }
    ],
    "ack": false
  }
}

**Comment by mehmetcelikel** [comment]
There were to much data in response of sparql query and some of them were too messy. I removed tags that have unknown context and the problem is fixed. We are currently processing dbpedia ontology and yago class hierarchies.
