### ISSUE TITLE
Prepare mock up for mobile application

### ISSUE THREAD

**Issue by cakyel** [swe574-2015fall-group2/core_repo#28]
First we will start with the basics such as list discussions / notes / meetings. create new discussion / note / meeting, comment and send messages.

**Comment by cakyel** [comment]
The link to Piazza mock up note and further discussions:
https://piazza.com/class/if3ll4yun9p306?cid=27

**Comment by OrkunKocyigit** [comment]
As for realistic mobile application user interfaces, the software called Pencil can be used, here is the link:

http://pencil.evolus.vn

**Comment by recepgunay53** [comment]
You can see mobile application mockups by following link:
https://drive.google.com/file/d/0BxserXWRSK5naldTeGNSY2hCU3c/view?usp=sharing

**Comment by cakyel** [comment]
Thanks Recep! The final 1.0 version can be found here:

https://piazza.com/class/if3ll4yun9p306
