### ISSUE TITLE
[Due 26.10.2015 Class] Our first deployment needs to be done

### ISSUE THREAD

**Issue by cakyel** [swe574-2015fall-group2/core_repo#37]
Login authorization will be deployed as a start via cloud server. Everyone will be able to commit after this issue is done.

**Comment by OrkunKocyigit** [comment]
What is the scope of first demo?

**Comment by cakyel** [comment]
I think this question is not suitable for this issue. This is only a test deployment.

**Comment by cakyel** [comment]
Job done.
https://piazza.com/class/if3ll4yun9p306?cid=63
