### ISSUE TITLE
[Due 26.10.2015 Class] Draft DSD document needs to be prepared

### ISSUE THREAD

**Issue by cakyel** [swe574-2015fall-group2/core_repo#42]
As we are gliding more and more into the project, DSD document needs to be prepared as a draft first.

Orkun is initially assigned as the Assignee but all of us should contribute this issue.

The draft document can be found in the link below.

https://docs.google.com/document/d/1rKGvySdR2UceM6NdcHlcxdZnt5D4ownLtGuSY2s1n98/edit#

**Comment by OrkunKocyigit** [comment]
What will be the contents of the Draft DSD?

**Comment by cakyel** [comment]
Have you seen the Google Docs document which I have included above? İn my opinion we don't have to cover all topics in the Draft version.

**Comment by OrkunKocyigit** [comment]
I saw it and where as it contains random information about our current topic, it doesn't give any information about general process of how DSD should be designed. The purpose of the template is only to state what is the overall data that should be in DSD and what processes should be followed and nothing else henceforth it serves different purpose.

**Comment by OrkunKocyigit** [comment]
The following topics are missing from RSD which prevents creation of the DSD, List may be update:

-Data attributes of Class Group is not defined.

**Comment by OrkunKocyigit** [comment]
Draft is finished, can be accessible from same link.

**Comment by cakyel** [comment]
Piazza link:
https://piazza.com/class/if3ll4yun9p306?cid=45
