### ISSUE TITLE
[Due Demo Release] Draft SPM document needs to be prepared

### ISSUE THREAD

**Issue by cakyel** [swe574-2015fall-group2/core_repo#43]
As we are gliding more and more into the project, SPM document needs to be prepared as a draft first.

Can is initially assigned as the Assignee but all of us should contribute this issue. It is due to demo release, we may change it later on.

The draft document can be found in the link below.

https://docs.google.com/document/d/1R4wp-3Bxks84AyPFHDlrBPTbM-eOLxQ8QqMnagd0q5Q/edit#

**Comment by OrkunKocyigit** [comment]
Here is SMP document template, may need to be revised.

https://www.dropbox.com/s/7lnprf5hjeg0lze/Caglayan-E1-XYZAPP-SPM-2015-03-16-Rev-1.0.doc?dl=0

**Comment by cakyel** [comment]
Have you seen the Google Docs document which I have included above?

**Comment by cakyel** [comment]
This issue is closed because it will have other issues regarding to the project plan.
https://docs.google.com/spreadsheets/d/1Ig3BvB5tYylSIy7crYtjCyBx0mMZsm-ONaj7zklSspE/edit#gid=1495075393
