### ISSUE TITLE
Web Project - Change Requests

### ISSUE THREAD

**Issue by cakyel** [swe574-2015fall-group2/core_repo#72]
Change requests should be completed based on customer feedback.

This issue is cooperated by Sinan and Recep.

**Comment by barisozcanli** [comment]
@cakyel what are the change requests?

**Comment by cakyel** [comment]
@barisozcanli When we were creating the plan at start, we assumed that there will be a need for change requests in the last milestones. Now we have many issues in detail so this one is obsolete. I am closing this issue.
