### ISSUE TITLE
[MILESTONE 3] - Meeting Management - Create Meeting

### ISSUE THREAD

**Issue by cakyel** [swe574-2015fall-group2/core_repo#80]

**Comment by barisozcanli** [comment]
@mehmetcelikel I reviewed and did come refactoring on your code. Please review the changes and close this issue.

Thanks for the initial code!

**Comment by barisozcanli** [comment]
btw, current functionality is a bit basic. We should improve the duration, location items. If these items are not planned yet we should plan them.

**Comment by mehmetcelikel** [comment]
Initial implementation is done. I will check against DSD and add more details.
