### ISSUE TITLE
[MILESTONE 3] -  User Role Management - List Custom User Role

### ISSUE THREAD

**Issue by cakyel** [swe574-2015fall-group2/core_repo#84]

**Comment by barisozcanli** [comment]
Role service
/v1/role/roles/all

@mehmetcelikel  please review and close the isue

**Comment by mehmetcelikel** [comment]
@barisozcanli General response template should be applied. I added this comment as todo in source code. That is why I am closing this issue.

**Comment by barisozcanli** [comment]
estimation : 0.5 hours
real effort : 0.5 hours
