### ISSUE TITLE
[MILESTONE 3] -  User Role Management - Delete Custom User Role

### ISSUE THREAD

**Issue by cakyel** [swe574-2015fall-group2/core_repo#85]

**Comment by barisozcanli** [comment]
Role service
/v1/role/role/{id}

@mehmetcelikel please review and then close the issue

**Comment by mehmetcelikel** [comment]
@barisozcanli 
Delete operation should check if a user has a role which will be deleted, This is already in todo list in source code, that is why I am closing this issue.

**Comment by barisozcanli** [comment]
estimation : 0.2 hours
real effort : 0.2 hours
